
services:
  mssql_server:
    build: .
    ports:
      - 4433:1433
    healthcheck:
      test: cat /usr/src/app/initialized | grep -q Initialized && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "password123!" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  echo:
    image: busybox
    depends_on: 
      mssql_server:
        condition: service_healthy
    command: [ "sh", "-c", "while true; do echo 'Hello from busybox'; sleep 5; done" ]
    healthcheck:
      test: echo "Hello from busybox"
      interval: 1s
      timeout: 30s
      retries: 5
      start_period: 30s