// <auto-generated />
using BIManagement.Modules.DataIntegration.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIManagement.Modules.DataIntegration.Persistence.Migrations
{
    [DbContext(typeof(DataIntegrationDbContext))]
    [Migration("20240612154825_AddTargetDbTablesAndSchemaMappings")]
    partial class AddTargetDbTablesAndSchemaMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dataIntegration")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BIManagement.Modules.DataIntegration.Domain.DatabaseConnection.CostumerDbConnectionConfiguration", b =>
                {
                    b.Property<string>("CostumerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.HasKey("CostumerId");

                    b.ToTable("DatabaseConnectionConfigurations", "dataIntegration");
                });

            modelBuilder.Entity("BIManagement.Modules.DataIntegration.Domain.DbModelling.CostumerDbModel", b =>
                {
                    b.Property<string>("CostumerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DbModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CostumerId");

                    b.ToTable("CostumerDbModels", "dataIntegration");
                });

            modelBuilder.Entity("BIManagement.Modules.DataIntegration.Domain.Mapping.SchemaMapping", b =>
                {
                    b.Property<string>("CostumerId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TargetDbTableId")
                        .HasColumnType("int");

                    b.Property<string>("Mapping")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CostumerId", "TargetDbTableId");

                    b.ToTable("SchemaMappings", "dataIntegration");
                });

            modelBuilder.Entity("BIManagement.Modules.DataIntegration.Domain.Mapping.TargetDbTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TargetDbTables", "dataIntegration");
                });
#pragma warning restore 612, 618
        }
    }
}
